# Generated by Django 4.2.5 on 2023-09-26 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentiment_analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentiment',
            name='confidence',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='sentiment',
            name='negative',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='sentiment',
            name='neutral',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='sentiment',
            name='positive',
            field=models.FloatField(null=True),
        ),
    ]
